package example;


/**
* example/Fibonacci.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/dev/workspace1902/repos/corba/CorbaFiboInterface/src/fibonacci.idl
* martes 10 de agosto de 2021 11:42:54 PM CDT
*/

public interface Fibonacci extends FibonacciOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Fibonacci
