package example;


/**
* example/Fibonacci.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:\Users\IRM-01\Documents\Uni K019\6to\Sistemas Distribuidos\Proyecto\Interfaces_Java\CORBA\CorbaFiboInterface\src\fibonacci.idl
* martes 10 de agosto de 2021 11:42:54 PM CDT
*/

public interface Fibonacci extends FibonacciOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Fibonacci
