package example;


/**
* example/FibonacciOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:\Users\IRM-01\Documents\Uni K019\6to\Sistemas Distribuidos\Proyecto\Interfaces_Java\CORBA\CorbaFiboInterface\src\fibonacci.idl
* martes 10 de agosto de 2021 11:42:54 PM CDT
*/

public interface FibonacciOperations 
{

  /* Codigo fibonacci CORBA
  		* in: el valor del parametro se le envia el
  		* cliente al servidor
  		* long: -231...231-1 (32bits)
  		* numero: nombre de la variable
  		*/
  String generar (int numero);
} // interface FibonacciOperations
